import "../Assets/Styles/globals.css";
import {Montserrat} from "next/font/google";

export const metadata = {
  title: "Movie Api",
  description: "Generated by Next.js",
};

const montserrat = Montserrat ({
  weight:["400","700"],
  subsets:["latin"],
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={montserrat.className}>{children}</body>
    </html>
  );
}
